# Конфигурация SnapshotD
# Используйте абсолютные пути.
# Если в пути есть пробелы, экранируйте их символом \.

SOURCE=/home/your_user/Documents/source_dir
TARGET=/home/your_user/Backups
FREQUENCY=15min
